const routerAdmin = {
    DASHBOARD: '/dashboard',
    USERS: '/quan-ly-nguoi-dung',
    ORDERS: '/quan-ly-don-hang',
    PRODUCTS: '/san-pham',
    LOGIN: '/dang-nhap-admin',
    REGISTER: '/dang-ky-admin',
    CATEGORIES: '/quan-ly-danh-muc',
    ACCOUNT: '/thong-tin-tai-khoan',
    CHANGE_PASSWORD: '/doi-mat-khau-admin',
    PARTNER: '/partner/partner-order',
    FORGOT_PASSWORD: '/quen-mat-khau',
    REGISTER_ADMIN :'/dang-ky-admin',
    DISCOUNT: '/quan-ly-giam-gia',
    VOUCHER: '/quan-ly-voucher',
    ARTICLES: '/quan-ly-bai-viet',
    BRANDS: '/quan-ly-thuong-hieu',
    ARTICLE: '/quan-ly-bai-viet',
    VERIFY_EMAIL: (email: string) => `/dang-ky-admin/xac-thuc-${email}`,
}
